### ISSUE TITLE
vault verify client cert

### ISSUE THREAD

**Issue by shsjshentao** [Boostport/kubernetes-vault#100]
if the option tls_require_and_verify_client_cert of my vault is open, how to configure kubernetes-vault?

**Comment by F21** [comment]
By `open` do you mean set to `true`?

Kubernetes-vault does not perform tls client authentication against the server. The assumption is that you've generated a token for kubernetes-vault (and only kubernetes-vault knows the value of the token) and if Vault is served over https, then the connection is secure.

I have not tried it yet, but I think Vault can support multiple listeners. In this case, you can create a listener with `tls_require_and_verify_client_cert` set to `false` for kubernetes-vault.

**Comment by shsjshentao** [comment]
Yes, i have seen the source code, Kubernetes-vault does not support this configuration.
Thanks
