### ISSUE TITLE
Quickstart failing

### ISSUE THREAD

**Issue by taylorKonigsmark** [Boostport/kubernetes-vault#113]
I can't start the quick-start deployment in minikube

Prerequisites 
- have minikube v0.25.0
- have vault v0.9.3

Reproduction steps:
- run setup.sh script found in quick-start folder

```
Error writing data to intermediate-ca/intermediate/set-signed: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/intermediate-ca/intermediate/set-signed
Code: 400. Errors:

* no data found in PEM block
```

Would anyone know the problem that could be causing this?

**Comment by F21** [comment]
This seems to be due to changes in the latest version of Vault. I am currently investigating and will fix the script.

**Comment by taylorKonigsmark** [comment]
Thanks @F21!
