### ISSUE TITLE
Better way to create namespace specific approle in vault

### ISSUE THREAD

**Issue by ssubramanian123** [Boostport/kubernetes-vault#115]
Hi,

I have a requirement to create approle specific to namespace.  Here is my scenario.

I have application helloworld and storing helloworld secrets in vault.  Now I am deploying helloworld in namespace 1 "ns1", it has vault approle as helloworld.  This deployment works fine. 

Later we decided to deploy helloworld also in namespace 2 "ns2".  Since vault is specific to this cluster, I am not able to create again "helloworld" as approle. Sometimes, secret may be different between ns1 and ns2 so I need seperate approle.

So I have created secrets as ns1_helloworld and ns2_helloworld.  But I feel there should be better way to create approle.

Is there any logic inside vault to seperate the approle based on namespace? Please check and confirm.

**Comment by F21** [comment]
I am not sure what you're trying to do here. Do you mean `kubernetes-vault` when you use the term `vault`? Kubernetes-Vault does not manage the creation of your AppRoles. It's something you need to manage yourself.

If you want `kubernetes-vault` to watch multiple namespaces, you can use regex. See: https://github.com/Boostport/kubernetes-vault#kubernetes-required

**Comment by F21** [comment]
Closing this as it has gone stale.
