### ISSUE TITLE
App Token

### ISSUE THREAD

**Issue by nikoskalenzis** [Boostport/kubernetes-vault#119]
Hello,

I am using the kubernetes-vault-init container to retreive a token for the api's upon container creation . I have followed the instructions and created an app-role for each api deployment. I can see the vault-token being created and mounted using the role-id from the app-role. The token is renewable, however after the lease duration ends, it is no longer usable, i get permission denied using it. Can anyone suggest what i'm doing wrong here or how to resolve this?

**Comment by F21** [comment]
Hey @nikoskalenzis 

This is how vault works, to limit the total lifespan of a token. For example, if a token is compromised, an attacker would only be able to use and renew it up to the lease duration.

Your options are:
- Get a new token from Vault before at a threshold before the lease duration ends. Some possible ways to do this are:
  - Terminate the instance of the app.
  - Write some code inside your app to seamlessly request a new token (you might need to set up permissions in Vault to allow you to do this).

- Use a periodic token. See: https://www.vaultproject.io/docs/concepts/tokens.html#token-time-to-live-periodic-tokens-and-explicit-max-ttls

**Comment by nikoskalenzis** [comment]
Hey @F21 

Thanks for the quick response, 
I think it'll have to be done within the app.
thanks and kind regards,
Nikos
