### ISSUE TITLE
Unable to unwrap wrapped secret_id after pod restart

### ISSUE THREAD

**Issue by colingabr** [Boostport/kubernetes-vault#123]
Ideally I'd like to use the wrapped secret_id functionality because it is the most secure. You can start a server with the role_id and wrapped_secret_id arguments or environment variables and then the actual secret_id will only exist in memory. 

However, I am concerned that it could potentially pose a reliability risk. If a pod restarts the secret_id will no longer be able to be unwrapped (the init-container will not run again to provision a new unwrapping accessor), you can't store the secret_id otherwise then there'd be no point. 

I know this issue is mostly due to how init-containers work in kubernetes, but I'm hoping there may be a method to solve this.

**Comment by F21** [comment]
I don't think this is something that can be easily solved. 

I think the best solution at the moment is to wait for the [kubernetes auth backend ](https://github.com/hashicorp/vault-plugin-auth-kubernetes) and [bounded service tokens](https://github.com/kubernetes/kubernetes/issues/58790) to mature. Once those pieces are available, we no longer need kubernetes-vault and the init containers.
