### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by noqcks** [Boostport/kubernetes-vault#124]
Is this project still alive?

What does it offer over https://www.vaultproject.io/docs/auth/kubernetes.html?

**Comment by F21** [comment]
Hey @noqcks

This project is still maintained as Vault's Kubernetes auth is not production ready yet. Once Vault's Kubernetes auth supports [TokenRequest](https://github.com/kubernetes/kubernetes/issues/58790) and TokenRequest is in beta, I think it would be a good idea to move to Vault's Kubernetes Auth.

At the moment, bugs are still being fixed, but we are not planning to put significant effort into new features.
