### ISSUE TITLE
sidekick and kubernetes-vault difference

### ISSUE THREAD

**Issue by jeusdi** [Boostport/kubernetes-vault#125]
I'm using [sidekick](https://github.com/UKHomeOffice/vault-sidekick) in order to get secrets.

I've been able to propagate secrets into files correctly. Nevertheless, I've not been able to figure out how to extract this content file and propagate it again as environment variables.

By other hand, I also don't understand why `sidekick` is shown like an addon inside `kubernetes-vault`. Which's the difference between them? Which is the goal of both?

**Comment by F21** [comment]
Sidekick is used to retrieve secrets from Vault. Kubernetes-vault only gets a Vault token into your pods. I haven't really used sidekick, but I think you should open an issue in the sidekick repo as this seems to be about how to use sidekick.

**Comment by F21** [comment]
Closing this due to staleness.
