### ISSUE TITLE
kubernetes-vault-init is not working if Pod is in a different NS

### ISSUE THREAD

**Issue by pradeepnnv** [Boostport/kubernetes-vault#128]
kubernetes-vault-init is not able to extract secret_id if Vault is in a different namespace.

Suggested fix: 
Update Vault url in kubernetes-vault CM to use FQDN.

Current value: 
addr: http://vault:8200
New value: 
addr: http://vault.default.svc.cluster.local:8200

**Comment by F21** [comment]
You can set the `vault.addr` value to the FQDN in your `kubernetes-vault.yml`. See https://github.com/Boostport/kubernetes-vault#kubernetes-required

The FQDN will be injected into the init container, as long as you set the full FQDN in your `kubernetes-vault.yml`.
