### ISSUE TITLE
Quick-start - Error while deploying Kubernetes-Vault - RBAC permissions

### ISSUE THREAD

**Issue by FabianHutin** [Boostport/kubernetes-vault#130]
Following the quick start vault deployment (https://github.com/Boostport/kubernetes-vault/tree/master/deployments/quick-start), there is a requirement for applying the command : kubectl apply -f deployments/quick-start/kubernetes-vault.yaml

kubectl apply -f kubernetes-vault.yaml 
serviceaccount/kubernetes-vault unchanged
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-vault configured
service/kubernetes-vault unchanged
configmap/kubernetes-vault unchanged
deployment.extensions/kubernetes-vault unchanged
Error from server (Forbidden): error when creating "kubernetes-vault.yaml": clusterroles.rbac.authorization.k8s.io "kubernetes-vault" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["get"]}] user=&{fabian.hutin@adeo.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]

Executing the command : 
kubectl create clusterrolebinding fabian-admin-access --clusterrole cluster-admin --user fabian.hutin@adeo.com
clusterrolebinding.rbac.authorization.k8s.io/fabian-admin-access created

resolves the problem.

**Comment by F21** [comment]
Hey, thanks for opening this issue. Can you open a PR to update the quickstart guide to include the command for the creation of the clusterrolebinding?
