### ISSUE TITLE
AWS admin has access to all secrets?

### ISSUE THREAD

**Issue by m0a0k0s** [Boostport/kubernetes-vault#133]
Hello, am I right that AWS admin has access to all secrets?
According to https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/README.md, te root token or admin token is written in yaml
deployment files
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token
in vault.yaml file 
So AWS admin could read this config from running service and use the token to read all secrets from vault?
Even if value will be in kubernetes secret AWS admin still will be able to access this token.

**Comment by F21** [comment]
That environment variable to to set a fixed well known root token for Vault in development mode. In production, you will need to have vault generate its own root token. You do need to generate a token for the kubernetes-vault controller, but you can scope it to just the permissions it requires from vault using vault's policies.

**Comment by m0a0k0s** [comment]
@F21 I’m sorry, I don’t understand what you mean in phrase “to have vault generate its own token”. 
From docs (https://www.vaultproject.io/docs/concepts/tokens.html) “The initial root token generated at vault operator init time -- this token has no expiration”. So vault generate this token and then administrator configure vault controller with it, for example:
- name: VAULT_DEV_ROOT_TOKEN_ID
value: 2b9b85ca-d25f-4958-bff9-a2c0cd618996

Then any AWS administrator can read this config and login to Vault, executing command: vault login 2b9b85ca-d25f-4958-bff9-a2c0cd618996. And read all data.
I could use limited admin token (https://www.vaultproject.io/guides/identity/policies.html) that by itself do no have policy to read all secrets. But this token should have policy to issue other tokens that could read any secrets. So it just extra step to manually issue one more token with necessary rights and read everything. If this admin token will not have rights to issue such token then how vault-controller will provide necessary token to init container? Who generate tokens for app/services?
Could you point any info what this limited permissions should looks like?

Does it mean yaml configuration in production won't contain tokens? Do you have any example of prod configuration?

**Comment by F21** [comment]
I am assuming you mean `VAULT_DEV_ROOT_TOKEN_ID` here: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/vault.yaml#L39

This setting has no relation to kubernetes-vault. That is used to set the root token in Vault under  [development mode](https://www.vaultproject.io/docs/commands/server.html#dev-root-token-id) to simplify things for a quick demo.

Kubernetes-Vault does need a periodic Vault token to talk to Vault, which is set here: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/kubernetes-vault.yaml#L54 . We've used the root token we set in Vault previously for convenience, but in production, you would need to create a token specifically for it. See: https://www.vaultproject.io/docs/commands/token/create.html

An example of the policy required for this token is here: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/policy-sample-app.hcl

I am not familiar with AWS, but if someone gains super admin access to your cluster, then in most cases, you'd have a major compromise and your secrets in Vault should be considered exposed, unless Vault was sealed at the time.

**Comment by m0a0k0s** [comment]
Ок, it’s clear with configuration. My initial question is more about security design and limits. There is a design request in my case to limit administrators from accessing client secrets, and probably it’s quite unrealistic task, but I must check it.
Because administrator has access to yaml config (token stored in plain text in it) and kubernetes secrets (more advanced reference in yaml to kubernetes secrets), he could read this vault-controller token and use it to access Vault API directly, that's only condition related to AWS.

I checked the yaml in this example (https://www.vaultproject.io/guides/identity/authentication.html#prerequisites). With a token with such rights, I will refer to it as admin token, administrator can create any app role by himself and read any secrets. 
I haven’t understood the whole security flow in boostport yet.
In your quick-start example, the role is created manually and hcl policy provide only a few rights. With manually created role we need administrator who own admin token and regularly use it to add new approle policies for newly created services. 
Even if it will be somehow possible to solve this problem, anyway, with vault-controller token administrator could get approle from pod.boostport.com/vault-approle annotation, get role id, create secret id for role and request token for role and so get access to all secrets available for this role (with 
 commands: vault read auth/approle/role/my-role/role-id
vault write -f auth/approle/role/my-role/secret-id
vault write auth/approle/login role_id=db02de05-fa39-4855-059b-67221c5c2f63 secret_id=6a174c20-f6de-a53c-74d2-6018fcceff64). Am I correct for this particular case or using boostport somehow make it more difficult to do this? 

P.S I've checked all command with vault-token and they allow to get this data. Next rule allow to execute them all
path "auth/approle/role/sample-app/secret-id" {
  capabilities = ["update"]
}
It seem's not possible to solve mentioned task.

**Comment by F21** [comment]
The token for kubernetes-vault can be limited using a Vault policy. Unfortunately, due to the design of AppRole auth, if you have access to all the pieces, you can get a token. I don't think it would be possible to design a system without any trust in this scenario. You'd have to trust your administrators as well as the pods you are running in the cluster. If this is not acceptable, you can consider Kubernetes Auth: https://www.vaultproject.io/docs/auth/kubernetes.html

Kubernetes Auth does have its own downside as well, but it would be impossible to have a system where the components and operators have 0 trust in each other.

**Comment by m0a0k0s** [comment]
Thank you very much for explanations.
