### ISSUE TITLE
Are you going to share kubernetes-vault-init ?

### ISSUE THREAD

**Issue by sokoow** [Boostport/kubernetes-vault#137]
Hey, there's a reference in your dockerfiles to kubernetes-vault-init - I'm trying to automate vault initing process, and it'd be handy to see how you resolved that.  Greetings

**Comment by F21** [comment]
Hey, `kubernetes-vault-init` does not initialize Vault. It's a init container for each pod and the code is available here: https://github.com/Boostport/kubernetes-vault/tree/44be8b20dcdc67178c4fad40ab9bdfc5e2cd9608/cmd/init

If you want to automate Vault, I suggest looking at the following operators:
- https://github.com/coreos/vault-operator
- https://github.com/banzaicloud/bank-vaults
