### ISSUE TITLE
Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ghost** [Boostport/kubernetes-vault#138]
Hi.
I tried to run quickstart guide and it works ok, thanks for it.
Then I'm trying to use kubernetes-vault for existing production-ready Vault.
My prod-ready Vault works on https and I don't understand how can I connect client to Vault on this step: https://github.com/Boostport/kubernetes-vault/tree/master/deployments/quick-start#23-prepare-the-manifest-and-deploy
I tried to add `vaultCABackends`:
```
...
 data:
  kubernetes-vault.yml: |-
    vault:
      addr: ${VAULT_ADDR}
      token: ${VAULT_TMP_TOKEN}
      tls:
        vaultCABackends:
          - root-ca
```
But it still doesn't work.
```
cat yaml/vault/kubernetes-vault.yml | NAMESPACE=vault KUBERNETES_NAMESPACE=vault envsubst | kubectl apply -f -

$ kubectl logs kubernetes-vault-6dcf5fbd59-gbqvz
time="2018-10-23T08:32:06Z" level=debug msg="Discovered 0 nodes: []"
time="2018-10-23T08:32:06Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault.domain.org/v1/auth/token/lookup-self: x509: certificate signed by unknown authority"
```

What's a problem and how can I fix that?

**Comment by F21** [comment]
Hey @AmetPreply this depends on where the certificate used to secure Vault's HTTP interface comes from:

- If you created a CA elsewhere (using CFSSL or OpenSSL for example) and used that CA to issue a certificate for Vault, then set the value of `vault.tls.caCert` to the path CA bundle: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml#L52

- If you are using Vault as your CA, then the configuration you have posted is correct, assuming your root CA is mounted in Vault's `root-ca` path.

**Comment by ghost** [comment]
Thank you for super-fast response @F21 
When I installed production Vault I generated certificate for it like this:
```
openssl req -subj "/commonName=*/" -x509 -nodes -days 3650 -newkey rsa:2048 -keyout privkey.key -out cert.crt
aws s3 cp cert.crt s3://vault-${ENV}-resources/resources/ssl/cert.crt --sse AES256
```
But I'm not sure that this cert for CA.

I created CA like in quickstart guide:
```
vault login
vault secrets enable -path=root-ca -max-lease-ttl=87600h pki
vault write root-ca/root/generate/internal common_name="vault.domain.com" ttl=87600h exclude_cn_from_sans=true
vault write root-ca/config/urls issuing_certificates="${VAULT_ADDR}/v1/root-ca/ca" \
    crl_distribution_points="${VAULT_ADDR}/v1/root-ca/crl"
vault secrets enable -path=intermediate-ca -max-lease-ttl=43800h pki
```
And I tried to use `root-ca` as a `vaultCABackends`

**Comment by ghost** [comment]
I also tried to change vault token generated by vault to random string and error still the same. So I thinks something happened with token, WDYT?
```
...
 data:
  kubernetes-vault.yml: |-
    vault:
      addr: ${VAULT_ADDR}
      token: "some-random-generated-string"
```

**Comment by F21** [comment]
@AmetPreply Even with the wrong token, you'd still get the same TLS error because the Vault client in Kubernetes-Vault would refuses to connect to Vault because Vault is not presenting a trusted certificate.

Since you're using OpenSSL to generate the certificate for Vault, I believe you don't need to enable the CA backends in Vault. Since you do not appear to have  Root CA, the certificate you generated is essentially your "root". In this case, the value of `vault.tls.caCert` should be the path to the file at `s3://vault-${ENV}-resources/resources/ssl/cert.crt`. Since Kubernetes-Vault does not understand s3 urls (it only understands normal file paths on the local system), you will need to copy the contents of the certificate into your `kubernetes-vault.yaml`. See https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml#L145 for example.

**Comment by ghost** [comment]
I tried this way too.
```
data:
  kubernetes-vault.yml: |-
    vault:
      addr: ${VAULT_ADDR}
      token: ${VAULT_TMP_ROKEN}
      tls:
        caCert: /kubernetes-vault/ca.pem
...
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
    ... some data from s3://vault-${ENV}-resources/resources/ssl/cert.crt
    -----END CERTIFICATE-----
```
Still the same error.

**Comment by F21** [comment]
Did you mount the file correctly into the Kubernetes-Vault pod? See https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml#L187

**Comment by F21** [comment]
Another thing I noticed is that your common name is set to `/commonName=*/`. This should be the hostname of Vault. For example, if Vault is hosted in the Vault namespace at `vault.vault`, then it should be set to `vault.vault`. If it's an IP address, then it the IPs should be set as IP SANs.

**Comment by ghost** [comment]
>Did you mount the file correctly into the Kubernetes-Vault pod?

Yes. I didn't change volumes for it.

>Another thing I noticed is that your common name is set to /commonName=*/. This should be the hostname of Vault. For example, if Vault is hosted in the Vault namespace at vault.vault, then it should be set to vault.vault. If it's an IP address, then it the IPs should be set as IP SANs.

We don't run Vault in k8s, it's separate installation on AWS EC2 instance.

**Comment by F21** [comment]
I think it's most likely that the certificate for Vault is not set up correctly. Can you try to access Vault using CURL and see if it also returns a certificate error?

If you are accessing Vault using its IP address, then the certificate for Vault must include the IP address as  an IP SAN when you generate it.

**Comment by ghost** [comment]
```
curl -s -H "X-Vault-Token: 79290104-2102-491f-a805-11111111" https://vault.domain.com/v1/auth/token/lookup-self  | jq
{
  "request_id": "7f5d3a4a-2db4-995a-889c-cd6fbb84f000",
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "accessor": "4b144161-a7a6-288a-d032-a178aaef5999",
    "creation_time": 1540288099,
    "creation_ttl": 86400,
    "display_name": "token",
    "entity_id": "",
    "expire_time": "2018-10-24T09:48:19.787999365Z",
    "explicit_max_ttl": 0,
    "id": "79290104-2102-491f-a805-3f9f0246aaa",
    "issue_time": "2018-10-23T09:48:19.787998329Z",
    "meta": null,
    "num_uses": 0,
    "orphan": false,
    "path": "auth/token/create/kubernetes-vault",
    "policies": [
      "default",
      "kubernetes-vault"
    ],
    "renewable": true,
    "role": "kubernetes-vault",
    "ttl": 85408
  },
  "wrap_info": null,
  "warnings": null,
  "auth": null
}
```

**Comment by F21** [comment]
Is Vault's certificate added to the trust store of the machine you're running CURL on? If so that might explain why it's working with CURL.

Is it simply a self-signed certificate or is it signed by a root CA?

**Comment by ghost** [comment]
>Is Vault's certificate added to the trust store of the machine you're running CURL on?

Nope. I tried to run curl from my local machine and from Kubernetes hosts (master and nodes), and got a same json output.

>Is it simply a self-signed certificate or is it signed by a root CA?

Simply generated:
```
openssl req -subj "/commonName=*/" -x509 -nodes -days 3650 -newkey rsa:2048 -keyout privkey.key -out cert.crt
```

**Comment by F21** [comment]
Few more things I can think of:
- Did you run CURL from a pod in kubernetes? If not, can you try that?
- Can you set the `commonName` to `vault.domain.org` and regenerate the certificate to see if it works?

**Comment by ghost** [comment]
>Did you run CURL from a pod in kubernetes? If not, can you try that?

Yes. I tried it, and it works.

> Can you set the commonName to vault.domain.com and regenerate the certificate to see if it works?

Will try that.

P.S. Could you please edit your last message to `vault.domain.com` due to security issues?

**Comment by F21** [comment]
@AmetPreply Were you able to resolve this?

**Comment by ghost** [comment]
Oh, sorry. Sure.

**Comment by Grigore147** [comment]
@AmetPreply - can you share how did you managed to get this working?
