### ISSUE TITLE
configurable wrapping token TTL

### ISSUE THREAD

**Issue by jeinwag** [Boostport/kubernetes-vault#141]
Currently, the TTL of the wrapping token of the secret-id is fixed to 60 seconds.

Are there any strong opinions against making it configurable? 

We'd like to leave unwrapping to our applications, but unfortunately, 60 seconds is too short in some cases.

**Comment by F21** [comment]
This is now configurable using the `vault.wrappingTTL` configuration option: https://github.com/Boostport/kubernetes-vault#vault-required which is released in `v0.6.1`.

**Comment by jeinwag** [comment]
Wow that was fast, thanks a bunch!
