### ISSUE TITLE
metrics go server.ListenAndServe()

### ISSUE THREAD

**Issue by llchen223** [Boostport/kubernetes-vault#143]
I couldn't get HTTP metrics to work for controller until I changed to a higher port:
```
        server := &http.Server{
+               Addr: ":8888",
                Handler: mux,
        }
```

Am I missing something here?

**Comment by llchen223** [comment]
nm, I'm using centos7 docker image.

**Comment by F21** [comment]
Usually, this is due to a permission issue that is preventing you from binding to a port lower than 1024. Were you able to fix the problem with the provided docker images?

See https://github.com/moby/moby/issues/8460
