### ISSUE TITLE
Problem with auth tokens with max TTL

### ISSUE THREAD

**Issue by llchen223** [Boostport/kubernetes-vault#144]
**Problem Statement**

We currently set max TTL on appRole auth tokens and cap its lifetime, these auth tokens are renewed (`renew-self`) periodically by a sidecar -- periodic tokens with unlimited or very long lifetime is not a good option for us.  Current design works well most of the time since our pods usually do not live longer than the token max TTL; however, we are seeing cases where some app. containers restarts (for whatever reason) after the token max TTL is already reached.  The restarted app. container is then left without a valid token, since neither the init-container or entire pod follow the app. container restart and go through the wrapped secrets exchange process again with the controller.

Has anyone else run into the same problem?  If so, what are the current solutions? And are most people using periodic tokens that are not capped by max TTL?

**Proposed Solution**

There are a few proposals relating to adjusting the max TTL... Here's my take on a solution:

Instead of pushing `wrapped_secret_id` to the init-container, have the init-container request `wrapped_secret_id` from the controller.  This requires the controller to expose a HTTPS service to internal pods and some way to authenticate requests.

Then use the same `wrapped_secret_id` request flow for sidecars to fetch new tokens before the current token reaches max TTL.

For authentication, passing the requesters pod service account token (PSAT) to the controller, then the controller would call TokenReview API to verify and derive a service account UID from PSAT.  This UID has to match the service account UID of an active pod.

To find a match, Controller would iterate over a list of active pods (`ListPods()`) and find the matching pod service account UID.  When there is a match, role is then extracted from the `vault-approle` annotation.  The remaining steps are the same as current design.

To be more efficient, the controller could use Kubernetes Informer and iterate over a cache of active pods rather than calling `ListPods()` for each incoming request.

The same source code can be shared between init-container (`wrapped_secret_id` request) and sidecar (`wrapped_secret_id` to controller and `renew-self` request to Vault), only difference is sidecar running on a non-stop cron.

I think these are the benefits to this solution:
- removes the need for RAFT quorum
- (w/o RAFT) each controller are independent and would probably simplify deployment
- init-container and renew/retrieve new token sidecar can have same codebase and executable

There is a security dependency on the way authentication is done using PSAT and TokenReview API.  If using PSAT decreases security, then need something else for authentication.  Do you have any thoughts here? 

I would appreciate feedback on this!
Thanks

**Comment by F21** [comment]
@llchen223 Thanks for opening this issue and for the detailed write up! At the moment, there are no plans to make extensive changes to the project as Kubernetes auth for Vault is maturing and will become the standard for authenticating pods against Vault in Kubernetes. 

Have you considered using Vault's built-in Kubernetes Auth? It seems very similar to your proposal:
- https://www.vaultproject.io/docs/auth/kubernetes.html
- Vault Agent sidecar: https://www.vaultproject.io/docs/agent/index.html

Using Vault's Kubernetes Auth would also eliminate Kubernetes-Vault and its moving parts within your cluster, potentially reducing administration and management overhead.

**Comment by llchen223** [comment]
@F21 No I'm not aware of the built-in Kubernetes auth; will take a look.  Thanks!

**Comment by llchen223** [comment]
Lesson learned: Google early... 😄

**Comment by F21** [comment]
I'll go ahead and close this issue. If you have any other concerns, please feel free to reopen. 👍
