### ISSUE TITLE
Error - undefined: raft.PeerStore

### ISSUE THREAD

**Issue by imriss** [Boostport/kubernetes-vault#145]
When executing `build.sh`, it gives an error related to `undefined: raft.PeerStore`:
```
# github.com/Boostport/kubernetes-vault/cmd/controller/cluster
cmd/controller/cluster/store.go:60:17: undefined: raft.PeerStore
```
it might be related to this change in `hashicorp/raft`:
`Remove the PeerStore: the peers.json file introduces the possibility of getting out of sync with the log and snapshot, and it's hard to maintain this atomically as the log changes. It's not clear whether it's meant to track the committed or latest configuration, either.`

[1] - [Removed PeerStore](https://github.com/hashicorp/raft/blob/a3fb4581fb07b16ecf1c3361580d4bdb17de9d98/membership.md)

**Comment by F21** [comment]
Hey @imriss, which version of Go are you using? The dependencies are vendored using Go modules see https://github.com/Boostport/kubernetes-vault/blob/master/go.mod. This requires Go 1.11 onwards to build correctly.

**Comment by imriss** [comment]
Hi @F21 Thanks. It is on Go 1.11.5: The line 6 in the `build-dev-images.sh` file:
`docker run --rm -v "$PWD":/go/src/github.com/Boostport/kubernetes-vault -w /go/src/github.com/Boostport/kubernetes-vault golang:1.11.5-alpine ./build.sh`
Any advise? Thanks

**Comment by F21** [comment]
@imriss I've updated `build-dev-images.sh` to use the Go 1.11 image and `build.sh` to put the source code outside the `GOPATH`, so that it builds using the modules. If you're planning to use `build-dev-images.sh` directly, you'll need to update it to push to a repo other than `boostport/kubernetes-vault`, as this is hard-coded into the script.

**Comment by imriss** [comment]
Thanks @F21
