### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by Grigore147** [Boostport/kubernetes-vault#146]
Hi,

I've got a similar issue as https://github.com/Boostport/kubernetes-vault/issues/138 and a few more, however still not clear on how to fix this.

I have an existing Vault as a separate service outside of Kubernetes at: https://vault.domain.com
The SSL certificate is issued by Let's Encrypt Authority X3, is a wildcard cert for *.domain.com.
Vault works on 127.0.0.1:8200 behind Nginx (which handles SSL termination with Let's Encrypt certs).

I've followed the quick-start guide up to https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/README.md#23-prepare-the-manifest-and-deploy, where i've stuck because of error below:

> time="2019-03-03T12:59:09Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault.domain.com/v1/auth/token/lookup-self: x509: certificate signed by unknown authority"

Tried to add TLS cert, but not really clear which one to get for this...
`
data:
  kubernetes-vault.yml: |-
    vault:
      addr: https://vault.domain.com
      token: 91526d9b-4850-3405-02a8-aa29e74e17a5
      tls:
        caCert: /kubernetes-vault/ca.pem  // where to get this certificate?
`
OSX, Minikube.

Can somebody please share clear solutions on why it happens and how to fix it?

Thanks!

**Comment by F21** [comment]
If the certificates for vault are all signed using let's encrypt, then you should use the let's encrypt root certificate here: https://letsencrypt.org/certs/isrgrootx1.pem.txt as your `caCert`.

**Comment by Grigore147** [comment]
Thanks,

I've managed to get it working a bit earlier using certificate from Let's Encrypt (based on https://github.com/Boostport/kubernetes-vault/pull/32), in my case it was this one https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt.
