### ISSUE TITLE
Failed to create vault auth token because we timed out

### ISSUE THREAD

**Issue by haywoood** [Boostport/kubernetes-vault#152]
We deleted a pod on a deployment that uses `pod.boostport.com/vault-init-container` This had been working fine and dandy but the new pod failed to come up with the error:

```
level=fatal msg="Failed to create vault auth token because we timed out after 5m0s before receiving the secret_id. Exiting."
```

We deleted another pod for a deployment that also uses it, and it too could not start back up.

Looks like there's been a lot of activity in the Vault library y'all use, perhaps something is broken?

**Comment by F21** [comment]
@haywoood It's possible that the Kubernetes-Vault controller did not see the new pod being created. Can you check the Kubernetes-Vault controller logs to see if the new pod was being seen by the controller?

**Comment by haywoood** [comment]
Not sure I'm looking in the correct spot, but the logs for our kubernetes-vault deployment just have a lot of this

```
 severity:  "ERROR"  
 textPayload:  "time="2019-06-17T23:51:03Z" level=debug msg="2019/06/17 23:51:03 [ERR] raft: Failed to make RequestVote RPC to *omitted*: dial tcp *omitted*: getsockopt: connection refused"
```

**Comment by F21** [comment]
It looks like the Kubernetes-Vault control has failed at some stage. When did it start failing? Were there any logs before the first `connection refused` entry that could point to what might be wrong? Also, around the time the `connection refused` errors started showing up, was the network topology in the cluster changed?

**Comment by haywoood** [comment]
things have been sideways for a while, the beginning of the logs shows this event

```
2019-05-19 10:45:34.421 EDT
time="2019-05-19T14:45:34Z" level=error msg="Could not push wrapped secret_id to pod (<>): error POSTing wrapped token: Post https://<>:50000: dial tcp <>:50000: getsockopt: connection refused"
```

**Comment by F21** [comment]
Hmm. This looks like a networking issue to me. Were there any changes to the network topology around that time?

**Comment by haywoood** [comment]
Possibly, going to talk with the team once some of them come online. Really appreciate the quick responses, very generous of you, won't bug you anymore tonight :D

**Comment by F21** [comment]
Not a problem at all! If the network topology did change, maybe (this may not be the best solution) it's possible to delete and redeploy the Kubernetes-Vault controller's deployment and let it "see" the new network to get it working again.

**Comment by F21** [comment]
@haywoood Were you able to fix/resolve this?

**Comment by haywoood** [comment]
Sort of, bringing up a new pod allowed projects downstream to connect.

**Comment by haywoood** [comment]
Thanks again for your help, I'll close this and possibly report back anything interesting we find while digging into it.
