### ISSUE TITLE
How to config backend for kubernetes vault

### ISSUE THREAD

**Issue by anemptyair** [Boostport/kubernetes-vault#153]
Hi,
I have two questions about kubernetes vault.
1. How to config backend like "asw dynamodb" for kubernetes vault?
2. Kubernetes vault will unseal automatically? I didn't see the unseal process?

Thanks.

**Comment by F21** [comment]
Hello and thanks for your interest in Kubernetes-Vault.

> 1. How to config backend like "asw dynamodb" for kubernetes vault?

This is part of the Vault configuration. If you want to configure DynamoDB as your config/storage backend you need to configure Vault, following these instructions: https://www.vaultproject.io/docs/configuration/storage/dynamodb.html

Kubernetes-Vault does not configure Vault for you. All it does is automatically grab Vault tokens and inject it into your pods.

> 2. Kubernetes vault will unseal automatically? I didn't see the unseal process?

Kubernetes-Vault will not handle the unsealing for you. You can use auto-unseal that is built into Vault if you are running in a support environment: https://www.vaultproject.io/docs/configuration/seal/index.html

**Comment by anemptyair** [comment]
I see ,thank you , kubernetes-vault is just talking to vault server which need to be set up firstly.
