### ISSUE TITLE
could not complete renewal operation: error issuing certificate

### ISSUE THREAD

**Issue by usmansiddiqui1** [Boostport/kubernetes-vault#156]
Could not renew certificate: could not complete renewal operation: error issuing certificate: Error making API request.\n\nURL: PUT http://infra-vault.kube-system:8200/v1/intermediate-ca/issue/kubernetes-vault\nCode: 400. Errors:\n\n* cannot satisfy request, as TTL would result in notAfter that is beyond the expiration of the CA certificate at

We were having these errors in controller log and I had to renew the cert manually. My question is what is the process and shouldn't it be automatic?

**Comment by F21** [comment]
Hey, the Vault controller should renew the certificate manually. From the looks of it, it looks like you're trying to issue a certificate that is past the expiry of the CA certificate. In your case, you should set up your root CA to have a long expiry and your intermediate CA to have a expiry that is pretty long, but less than the root CA's expiry.

**Comment by usmansiddiqui1** [comment]
I deployed this same project so root is expiring in 10 years and intermediate CA in 5 years. Intermediate cert created and signed by root has expiry of 30 days.

**Comment by F21** [comment]
The code to issue the certificate is [here](https://github.com/Boostport/kubernetes-vault/blob/140852b310fb7a354736bad297f305332a24d418/cmd/controller/client/vault.go#L416), It does not set the expiry time and relies on the configuration in Vault to assign the expiry time.

Is your intermediate CA's certificate 5 years or 30 days? If it is 30 days, then it's possible the intermediate CA's certificate expired when it was time to renew the Kubernetes-Vault certificate.
