### ISSUE TITLE
Error: cannot use memberlistConfig

### ISSUE THREAD

**Issue by ghost** [Boostport/kubernetes-vault#17]
Doing a build of the controller getting this error

`# github.com/Boostport/kubernetes-vault/controller/cluster
cluster/gossip.go:37: cannot use memberlistConfig (type *"github.com/Boostport/kubernetes-vault/vendor/github.com/hashicorp/memberlist".Config) as type *"github.com/Boostport/kubernetes-vault/vendor/github.com/hashicorp/serf/vendor/github.com/hashicorp/memberlist".Config in assignment`

go version go1.7 linux/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/vagrant"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build964776315=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by ghost** [comment]
Okay finally got this to work but had to do it this way.

govendor fetch github.com/hashicorp/memberlist -Ossl.cert_reqs=none
govendor fetch github.com/hashicorp/serf -Ossl.cert_reqs=none
govendor fetch github.com/hashicorp/serf/serf -Ossl.cert_reqs=none

For reference where I got the info on this

https://github.com/hashicorp/serf/issues/386

**Comment by F21** [comment]
The project uses `glide` for dependency management. Because serf includes the vendor folder, you will need to do `glide install --strip-vendor`. However, if you have docker, you can use the `build.sh` script and it will spin up a container and build the binaries for you 😄

**Comment by F21** [comment]
I am closing this as it as been resolved. Please reopen if you have further problems with the vendoring 😄
