### ISSUE TITLE
Is it possible to share how we are generating certificates.

### ISSUE THREAD

**Issue by pandeybk** [Boostport/kubernetes-vault#25]
I am trying to use this project in our environment. Currently I am having trouble generating self signed certificate mentioned in vault.yaml and kubernetes-vault.yaml.

I know this is behind scope of this project and there are plenty of resources available online. But if possible is it possible to share exact steps or document process, so that we can generate our own certificate.

**Comment by F21** [comment]
hey @pandeybk , the [quick start guide](https://github.com/Boostport/kubernetes-vault/blob/master/quick-start.md) contains step-by-step instructions for using vault as a certificate authority. Does it help?

**Comment by pandeybk** [comment]
@F21 are you saying this guide actually cover certificate mentioned in following manifest file. Looks like in quick start guide we are using vault to generate certificate, while in below manifest file we are actually providing certificate as a part of k8 secret. 

https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml
https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/vault.yaml

**Comment by F21** [comment]
@pandeybk There are 2 ways to do this. You can use Vault as a CA and kubernetes-vault will automatically request and renew certificates from Vault. 

Configure the following sections in the configuration yaml:
- https://github.com/Boostport/kubernetes-vault#example-using-vault-as-a-ca
- https://github.com/Boostport/kubernetes-vault#example-1

The second way is to set up your own external CA and pass the certificate, key and CA bundle to kubernetes-vault via k8s secrets. This method is demonstrated in https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml and https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/vault.yaml

**Comment by pandeybk** [comment]
Ok nice thank you, I think I will go with first approach.

**Comment by F21** [comment]
Glad you got it working! 😄
