### ISSUE TITLE
Sample application, unable to create vault auth token (init pod not working)

### ISSUE THREAD

**Issue by pandeybk** [Boostport/kubernetes-vault#26]
Hi I am seeing following error when trying to deploy sample application.

time="2017-04-17T21:18:29Z" level=fatal msg="Failed to create vault auth token because we timed out after 5m0s before receiving the secret_id. Exiting."

**Comment by pandeybk** [comment]
I think I found the issue. I was trying to deploy all vault components in vault namespace and sample application in default namespace. When I moved sample application in vault namespace it start working.

**Comment by F21** [comment]
@pandeybk You can use regex to watch multiple namespaces. See https://github.com/Boostport/kubernetes-vault#kubernetes-required.

To use regex, set `watchNamespace` to be a regular expression prefixed with `~`.

In your case, if your app is in default, just set `kubernetes.watchNamespace` to be `default` and `vault.addr` to `https://vault.vault:8200`, assuming vault is in the `vault` namespace and your apps are only deployed to the `default` namespace.

If you want to watch both the `default` and `vault` namespaces, set `kubernetes.watchNamespace` to `~^(default|vault)$`

**Comment by pandeybk** [comment]
@F21 thank you and sorry for the trouble, clearly I keep skipping documents, I am trying this.  Running into following issue at this point. Which is I think actually valid, because example certificate possibly generated for vault not vault.vault. 

`
time="2017-04-17T23:02:43Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault.vault:8200/v1/auth/token/lookup-self: x509: certificate is valid for vault, localhost, not vault.vault" 
`
I will get back to you, once this is resolved.

**Comment by F21** [comment]
hey @pandeybk were you able to resolve this?

**Comment by pandeybk** [comment]
@F21 actually not. Some reason generated certificate is not working in my case. Here is my steps,

Generate CA first
```
$ openssl genrsa -out ca-key.pem 2048
$ openssl req -x509 -new -nodes -key ca-key.pem -days 10000 -out ca.pem -subj "/CN=vault-ca”
```
And generate self signed certificate and signed with CA.

```
$ openssl genrsa -out vaultserver-key.pem 2048
$ openssl req -new -key vaultserver-key.pem -out vaultserver.csr -subj "/CN=vault-apiserver" -config openssl.cnf
$ openssl x509 -req -in vaultserver.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out vaultserver.pem -days 365 -extensions v3_req -extfile openssl.cnf
```
And here is my openssl.cnf

```
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = vault
DNS.2 = vault.vault
DNS.3 = localhost
```

And I am using vaultserver-key.pem  and vaultserver.pem file content as private and public keys. Also ca.pem as CA content. I wonder if I am missing anything here.

**Comment by F21** [comment]
Hey @pandeybk,

I think it would be easier to use Vault to create those certificates. Can you spin up a standalone Vault server (on your machine) and follow 2.2 and 2.3 in the [quick start guide](https://github.com/Boostport/kubernetes-vault/blob/master/quick-start.md#22-set-up-the-root-certificate-authority)? After that, use the intermediate CA to generate a certificate and key as per the [official docs](https://www.vaultproject.io/docs/secrets/pki/index.html#generate-credentials).

Let me know how you go. 😄

**Comment by pandeybk** [comment]
@F21 issue resolved with some additional steps for vault-controller side car.

Sorry didn't get the chance to work with standalone vault server. 

```
openssl genrsa -out vaultcontroller-key.pem 2048
openssl req -new -key vaultcontroller-key.pem -out vaultcontroller.csr -subj "/CN=vaultcontroller" -config vaultcontroller-openssh.cnf
openssl x509 -req -in vaultcontroller.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out vaultcontroller.pem -days 365 -extensions v3_req -extfile vaultcontroller-openssh.cnf
```

**Comment by F21** [comment]
@pandeybk Good to hear! I'll close this issue. Please reopen if you run into something similar 😄
