### ISSUE TITLE
feature req: Extract actual secret values to specified volume mount

### ISSUE THREAD

**Issue by travis-bear** [Boostport/kubernetes-vault#28]
Give the user the option of extracting the specified secrets instead of just the token, so that when the init container completes, applications can find their secrets in expected locations without having to know anything about vault.

**Comment by F21** [comment]
This is a good idea, however I feel that it would make `kubernetes-vault` too complicated.

My current plan is to build a separate side-car container that will live in the pod, use the token from `kubernetes-vault` to get the secrets and write them to some predefined location. This container will also be able to optionally signal the main pod when secrets change (through renewals) using SIGHUP or another signal to reload those secrets. For example, a prime use-case for this would be to use Vault as a CA, generate short-lived certificates for applications and reload the certificates every 24 hours.

I haven't found the time to build this yet, but it's definitely on my roadmap!

**Comment by travis-bear** [comment]
I think your plan would work fine, but it does come with a implicit trade-off of lower implementational complexity for increased operational complexity.  Ideally I could protect my development teams from having to configure this sort of thing into their pods.

**Comment by F21** [comment]
At the moment, you would need to configure the kubernetes-vault init container for each pod in your deployments anyway, so my opinion is that configuring a second container should not be too onerous.

In the case of the secrets container, if you just want to get the secrets once on start-up, you can just run it as an init container. If you need it to renew secrets and/or reload the containers in the pod, you can just run it as a regular container.

In my opinion, it would allow for better composability and separation of concerns, as the Vault token does not necessary have to come from Kubernetes-Vault.

I am keen to hear about your case for lower operational complexity. Could you expand more on that?

**Comment by travis-bear** [comment]
We're discussing implementing an init container that wraps the standard kubernetes-vault init container, and extracts a specified set of secrets to a volume mount once the access token has been made available.

We'd be happy to post the new event container on docker hub where it could be used as an optional alternative to the standard init container, if you think there would be interest.

**Comment by F21** [comment]
@travis-bear That would be really awesome! I look forward to giving it a spin! 👍

**Comment by F21** [comment]
@darron has contributed a PR to https://github.com/UKHomeOffice/vault-sidekick that allows it to read the token information created by the kubernetes-vault container.

There are a few things missing, but I think it is pretty close to what I had in mind:
- Support renewing the Vault token
- Use more information from the token information written by kubernetes-vault:
  - vaultAddr
  - CA Bundle for Vault
  - Lease duration and renewable status of the token to determine whether the token should be renewed on a periodic basis or not.
