### ISSUE TITLE
RFI: init container logs

### ISSUE THREAD

**Issue by raffaelespazzoli** [Boostport/kubernetes-vault#3]
hi, 
I'm trying to use this project. 
My sample app pods are stuck in initilizing state. When I try to look at the logs of the init container nothing is printed.
Is there a way to increase the log verbosity of the init containers?
Or can this feature be added?

**Comment by F21** [comment]
@raffaelespazzoli Are you able to post the deployments and configs being used?

In anycase, more verbose logging is definitely a good thing!

**Comment by F21** [comment]
I've merged #9 which improves logging. However, by default, verbosity is already set to debug, so it should show all logs. 

The PR will allow you to configure the verbosity (either `debug` or `error`). I've also included some troubleshooting tips on how to view the init container logs here: https://github.com/Boostport/kubernetes-vault/blob/master/troubleshooting.md
