### ISSUE TITLE
Vault Unseal Operation

### ISSUE THREAD

**Issue by bdmyxgh** [Boostport/kubernetes-vault#40]
Can you please describe how unseal operation works with kubernetes-vault?

**Comment by F21** [comment]
Hello,

Kubernetes-Vault does not manage the unsealing or operation of your Vault cluster. You will have to do this manually yourself or build/find a Vault operator. See here for more information on operators: https://coreos.com/blog/introducing-operators.html

I think an operator would be the best way to manage Vault, but I've not found time to build one.
