### ISSUE TITLE
HA Model

### ISSUE THREAD

**Issue by bdmyxgh** [Boostport/kubernetes-vault#42]
Hello!
As it stated in the documentation, two components (controller and init container) are used. There is also a mention about Raft based HA model.
As I understand, the HA model applies to controller only?
Can the production setup have several init and controller containers in HA mode?
Please advise. 
Thanks!

**Comment by F21** [comment]
Hello!

Yes, you're correct. HA mode is for the controller only. In production, you can run multiple controllers in odd numbers for a quorum, for example, 1, 3, 5, 7, etc. However, for performance reasons when appending the raft logs , you should not have too many controllers. The FAQ for etcd should also be applicable in this case: https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-is-maximum-cluster-size

For the init containers, there is no point having HA for them. However, if for some reason you need to have multiple Vault tokens for a pod, then you can chain the init containers, 1 after another.

Hope that helps! 😄
