### ISSUE TITLE
Vault Secrets

### ISSUE THREAD

**Issue by bdmyxgh** [Boostport/kubernetes-vault#45]
Hello,
What secrets backend is used by Vault in this mode?
Can I have N active Vault servers?

**Comment by F21** [comment]
You can use any secret backend you want. The Kubernetes-Vault controller injects a Vault token into your pod, but you will need your own Vault client to use the token to get secrets.

Yes, you can run multiple Vault servers with 1 active and the others in standby, however, make sure to expose them behind a kubernetes service using the same name, for example: `vault.mycluster`.
