### ISSUE TITLE
Alternate and more secure solution

### ISSUE THREAD

**Issue by raoofm** [Boostport/kubernetes-vault#5]
@F21 Thanks for the great work, it made the solution look lot easier with such a clean workflow diagram.

I was just imagining this workflow and kind of discussed with my colleague and we envision that this could be more secure if you could limit the number of usages of secret and then the init container should just unwrap the secret and write the secret to the volume rather than writing the token itself (as the token can be stolen without the app noticing it).

So in this case the app itself will read the secret and get the token (number of usages of secrets is exhausted) and if someone stole the secret from the volume then the secret isn't usable by the app itself triggering a security alert.

The token fetched by the app could be a very short ttl or long based on usage. Most apps would use the token to fetch secrets from vault and then may not need the token unless the secrets are rotated.

Waiting for your opinion.

**Comment by raoofm** [comment]
@F21 ?

**Comment by F21** [comment]
Hey!

I am currently out of office and have a very sporadic internet connection. I will get back to you in a few days.

**Comment by F21** [comment]
@raoofm,

Can you clarify what you mean by secret? 

In the case of the init container, it receives the auth token from the kubernetes-vault controller and unwraps it. However, if I understand correctly, are you saying to not have the init container unwrap the auth token? In that case, we can add a configuration parameter to the init container to cause it just write the auth token to the shared volume and have the app unwrap the auth token itself.

**Comment by raoofm** [comment]
@F21 As per the below flow diagram step 3, wrapped secret_id is pushed to init container by vault controller.... secret_id is what I mean by secret.

The flow diagram also mentions that init container unwraps secret_id and uses the secret_id to get the token and writes the token to volume.

What I wanted to say is init container can write the secret_id to volume instead of writing token itself (secret_id should be set with max number of usages 1). So when the app reads the secret_id and gets the token the secret_id becomes practically unusable and token will be in app memory. This will make it more secure.

![image](https://cloud.githubusercontent.com/assets/12846989/23181170/f02b5ab2-f841-11e6-8cf6-5e7b04e5696f.png)

**Comment by F21** [comment]
Thanks for clarifying!

I think it would still be useful to keep writing the auth token to the volume for some use-cases so that the app won't have to concern itself with unwrapping the token from the secret_id.

I think adding a `UNWRAP_SECRET_ID` environment variable that is by default set to `true` should be able to support this. If you set it to false, it will not unwrap the secret_id and exchange it for an auth token, essentially, stopping after completing step 3 of the flow diagram.

Let me know what you think 😄

**Comment by F21** [comment]
This has been resolved by introducing an environment variable called `RETRIEVE_TOKEN` for the init container. By default this is set to true, but you can disable it by setting it to false.

In this case, the token format written to the volume is slightly different. See: https://github.com/Boostport/kubernetes-vault#token-format

This will be released as 0.3.0 in a few moments and the docker images will be built.
