### ISSUE TITLE
Securing Vault Role ID/Secrets

### ISSUE THREAD

**Issue by jcantosz** [Boostport/kubernetes-vault#51]
Hi, 
Thanks for the awesome project!

I have added AppRoles to Vault for my app, and created the pods described based on the quick-start guide. I would like to restrict access to Vault to a deployment, but am concerned that another user could dump my pod definition (`kubectl get pods sample-app-<id> -o yaml`) and use it to impersonate my AppRole. Is there any way to prevent this (users still need to access their pods)?

I have considered restricting each user/pod to its own namespace, but in that case, it may be easier to use built in secrets and encrypt those on disk. 

I would like to hear you opinion on this. It seems like with this model we are saying we trust the users, but not the pods, is that correct?

Thanks!

**Comment by F21** [comment]
Hey @jcantosz ,

This is a limitation of the AppRole model. In this case, we are assuming that users/pods within a namespace is trusted. The only suitable solution is to audit and restrict access to deploying to a namespace. It's something I've thought about and considered when the project was started, but this is currently the best solution (for example, other solutions have pods specify their policies directly).

My hope is that Kubernetes will gain deep integration with Vault in the future, rendering this project obsolete.

**Comment by jcantosz** [comment]
Thank you for the response!
