### ISSUE TITLE
Proper token role configuration

### ISSUE THREAD

**Issue by michaelansel** [Boostport/kubernetes-vault#53]
kubernetes-vault expects a token generated from a token role with the following constraints:
- must be renewable
- must be periodic (with period > 0)
- must not be an orphan

While the first two are totally logical, the third has me confused. Non-orphaned tokens are automatically revoked as soon as the parent expires/is revoked. This means that the kubernetes-vault token must be therefore associated with some other long-lived parent token. Since we are creating a "live forever" periodic token, that implies that the parent token is also either a "live forever" periodic token or a root token. Given that Hashicorp best practice is to never have an active root token post-initialization and I can't see any value in having a separate long-lived parent token that needs to be constantly refreshed, I'm a bit confused as to why there is a "no orphan" requirement: to me, creating an orphan is exactly what we want to do.

Can you explain the rationale here?

**Comment by F21** [comment]
Thanks for bringing this to my attention. The requirement for non-orphan tokens must have been inadvertently carried over from [Nomad's implementation](https://www.nomadproject.io/docs/vault-integration/index.html#vault-token-role-configuration) when the project was first created. I've removed this requirement in #54 and tagged `v0.4.7`.
