### ISSUE TITLE
Allow setting watchNamespace="" or multiple namespaces

### ISSUE THREAD

**Issue by munnerz** [Boostport/kubernetes-vault#58]
Hey

It'd be great if we could configure kubernetes-vault to either use the empty string for watchNamespace (which in k8s is NamespaceAll: https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L264), and/or a list of namespaces to watch (to save having to watch all!)

Implementing support for multiple namespaces may be trickier and require more code changes, but to allow "" should be relatively painless. Alternatively, some flag to allow setting all namespaces.

**Comment by F21** [comment]
Hey @munnerz 

The Kubernetes-Vault config allows you to use regex to define the watched namespace. If using a regex, simply prefix the namespace with a `~`, similar to nginx.

To watch all namespaces: `~.*`

To watch only the namespaces you want: `~(staging|default)$`

Does this help?

**Comment by munnerz** [comment]
Ah awesome! Sorry, I must have missed that in the codebase... I didn't notice any regex parsing etc.

Thanks very much.
