### ISSUE TITLE
Vault secured with external certs

### ISSUE THREAD

**Issue by jaxxstorm** [Boostport/kubernetes-vault#6]
I'd like to deploy this app, but unfortunately it makes quite a few assumptions about Vault TLS config.

I secure my vault HTTP API access with an external CA cert/cert/key. With the deployment method listed, I can't supply a CA bundle to verify access to it.

It would be good to not have such a reliance on the vault pki store, and have the option to pass a base64 or pem encoded CA/Cert using the TLSConfig option: https://godoc.org/github.com/hashicorp/vault/api#TLSConfig

**Comment by F21** [comment]
Thanks for your interest in this project. These are all very good points and the controller should definitely support using an external CA for dealing with TLS.

I think introducing new environment variables to support this would probably cause too much confusion.

Perhaps it's time to move all the configuration into a config file (in yaml format) and have it mounted to the container using kubernetes' ConfigMap?

**Comment by jaxxstorm** [comment]
Totally agree, a configmap is a great idea.

**Comment by jaxxstorm** [comment]
Alternatively, it seems possible to just make use of `ReadEnvironment` for less messing with env vars within the code?

https://godoc.org/github.com/hashicorp/vault/api#Config.ReadEnvironment

**Comment by F21** [comment]
I believe that reads in environment variables for configuring Vault. Since this controller is deployed separately to vault, we would have our own set of environment variables or configuration.

**Comment by F21** [comment]
I've merged PRs #7 and #8 to change configuration of the controller to use config files. Included is also support for using CA Root bundles, certificate files and keys. 

The documentation in the README has been updated to reflect this.

I am planning to resolve a few more issues before releasing 0.3.0 which will include this improvement.
