### ISSUE TITLE
imagePullPolicy set to Always in examples without rationale

### ISSUE THREAD

**Issue by JPhi1618** [Boostport/kubernetes-vault#61]
In the example app deployments, the imagePullPolicy is set to Always for the init container.  Does this need to be the case?

I believe this may be because some examples are not using a tag on the image, but if we use a version tag on the image is there a reason why Always is preferred?  Does the project anticipate making changes to existing versions that we need to pull?

The only "fix" for this is a line in the quick start or main readme explaining the reason for (or for not) using Always.

And, thanks for the effort on this.   We are using it with a good experience so far!

**Comment by F21** [comment]
@JPhi1618 The deployments are examples for testing out the system. The reasons for setting `imagePullPolicy` to `true` are:
- When building the dev images, they are tagged as `dev`, and having `imagePullPolicy` set to `true` allows for easier testing of those images during development.
- Previously, I had image versions pinned using tags in the deployments, but it is not fool-proof. There were a few times when I forgot to update those version numbers before tagging and pushing a release.

Each versioned image should be considered immutable. They will not be modified in any way after they are pushed. 

Having said that, the deployment files are only a guide for testing/setting up a cluster for playing with. In production, you'd most likely have specific requirements where you will have your own deployments.

Hope that helps! 😄

**Comment by JPhi1618** [comment]
Yes, thanks.  I just wanted to make sure there wasn't some nuance to Always that I was missing.  We haven't had a need to change the default in our own deployments and there's always a chance of some undocumented side effects that aren't obvious.

Thanks again.
