### ISSUE TITLE
feature req: provide a helm chart

### ISSUE THREAD

**Issue by alejandroEsc** [Boostport/kubernetes-vault#70]
I think it would be useful to provide a helm chart in order to deploy your service onto a kubernetes cluster.

Should help users a single place to maintain a set of configurations that will deploy kubernetes-vault  as they see fit.

I further submit that it would be best to keep the chart in the kubernetes/charts repo.

**Comment by alejandroEsc** [comment]
@F21 If you are ok, and excited about this prospect, I would like to help get this done! thanks for considering this feature.

**Comment by F21** [comment]
@alejandroEsc Super awesome! Having a chart in the official charts repo would be really really cool! 👍  I haven't had time to really play with helm + tiller, so I will have to leave that up to you!

**Comment by alejandroEsc** [comment]
Nearly complete, sorry for the delays, will send you the branch you can look at as soon as it is complete. Thanks for being patient!

**Comment by F21** [comment]
@alejandroEsc Thank you so much for working on this!

I just found a PR on kubernetes/charts for kubernetes-vault: https://github.com/kubernetes/charts/pull/1396

Perhaps you can join forces with @bbriggs 👍

**Comment by alejandroEsc** [comment]
@F21 LOL darn the pains of having priorities. Anyway, @bbriggs happy to help if you like.

**Comment by alejandroEsc** [comment]
@F21 i wanted to ask you, did you intend as in your samples for people to use your vault deployment?

**Comment by alejandroEsc** [comment]
@F21 decided to proceed since nearly done and let the community help reconcile the two, better to have more viewpoints: https://github.com/kubernetes/charts/pull/1592

**Comment by F21** [comment]
@alejandroEsc Thanks you so much for contributing the chart! 😄 

The sample vault deployment is very insecure and runs it in development mode, so it should be not be used directly in production. However, with some modification to lock it down, it should be good for production use. I feel that it would be nice to write a Vault operator to try and automate most of the setup process, but haven't found the time to build one yet.

**Comment by bbriggs** [comment]
Yes! I have a PR in to helm right now for this but it's sadly rotting away right now. I'll update the nits that you requested. 

I dropped into the k8s-helm core meeting a couple weeks ago to request review and they said they wanted to look at the full stack (vault + consul + kubernetes-vault) and evaluate it in context of that ecosystem but I haven't seen much movement.

**Comment by bbriggs** [comment]
I also had my chart point out to my external vault, but it can easily point to any Vault URL reachable from the cluster or pod.

**Comment by F21** [comment]
The helm chart is now in! See https://github.com/kubernetes/charts/tree/master/incubator/kubernetes-vault
