### ISSUE TITLE
missing client token

### ISSUE THREAD

**Issue by amolsh** [Boostport/kubernetes-vault#78]
Hi, I am following quickstart guid  to setup. 
Kubernetes version 1.5.4
when I fired : **vault mount -path=root-ca -max-lease-ttl=87600h pki**
i encountered following error:

![image](https://user-images.githubusercontent.com/10971917/29661610-33a822da-88e2-11e7-9bc6-785a3250f640.png)

What is cause for it ?

**Comment by F21** [comment]
I think this might be due to a client and server version mismatch.

Can you confirm that you're running the same versions of vault as the client and server?

**Comment by amolsh** [comment]
I have kubernetes Cluster in AWS
I have installed vault in Local Machine(Mac) 
I have installed vault as binary dowloaded from https://www.vaultproject.io/downloads.html 

**vault version**:  On local machine
Vault v0.8.1 ('8d76a41854608c547a233f2e6292ae5355154695')

**kubectl exec vault-3263313949-g2fgj vault version**: On POD
Vault v0.8.1 ('8d76a41854608c547a233f2e6292ae5355154695')

**vault status**:
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
Unseal Nonce:
Version: 0.8.1
Cluster Name: vault-cluster-e9f51023
Cluster ID: a6b3dea3-42fe-fd26-4925-92ddd1065a6c

High-Availability Enabled: false

**kubectl version**:
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4+coreos.0", GitCommit:"97c11b097b1a2b194f1eddca8ce5468fcc83331c", GitTreeState:"clean", BuildDate:"2017-03-08T23:54:21Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by F21** [comment]
It's possible that vault did not have a client token. Can you run `vault auth` and type in `vault-root-token` when prompted for the token and try again?

**Comment by amolsh** [comment]
@F21 Thanks , I missed that step , as it was not written in bullet points.

**Comment by F21** [comment]
@amolsh See https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/README.md#22-set-environment-variables-and-authenticate

I will close this issue for now 😄
