### ISSUE TITLE
Kubernetes-vault pod giving error: Could not create the vault client: error parsing supplied token

### ISSUE THREAD

**Issue by amolsh** [Boostport/kubernetes-vault#79]
Hi, I am following quickstart guid to setup.
Kubernetes version 1.5.4
Kubernetes-vault pods are crashing and I am getting following error in kubernetes-vault pods
 
![image](https://user-images.githubusercontent.com/10971917/29742524-756f5bc6-8a9e-11e7-99d8-196861a0e6a3.png)

i used **deployments/quick-start/kubernetes-vault-kube-1.5.yaml** file 
Everything is in default namespace 
![image](https://user-images.githubusercontent.com/10971917/29742569-4fdd99bc-8a9f-11e7-81b8-6401d5782f26.png)

![image](https://user-images.githubusercontent.com/10971917/29742567-2cca8bba-8a9f-11e7-9d0f-e9c331e5d194.png)

**Comment by F21** [comment]
The `server misbehaving` error seems to be a DNS issue. How is your kubernetes cluster setup?

**Comment by amolsh** [comment]
I am not sure, How should I troubleshoot DNS?
Our Cluster is on CoreOS which consists of 3 Master , 3 Controller and 10 worker. It is on AWS.
I tested following dig query by forwarding kube-dns port on local machine -
![image](https://user-images.githubusercontent.com/10971917/29749789-de4c695a-8b51-11e7-8a79-4112ecd14773.png)

**Comment by F21** [comment]
Since you've set kubernetes-vault to use the vault server at `http://vault:8200`, can you try the following?

1. Start a pod/deployment in the same namespace.
2. In the pod, use wget or curl to hit the vault api. For example, `curl http://vault:8200/v1/secret/baz`.

If it works correctly, curl should return a 403 or 404 (if you're not authenticated).

**Comment by amolsh** [comment]
Everything related to vault is in default Namespace
I set up ubuntu pod in default namespace and fired command

![image](https://user-images.githubusercontent.com/10971917/29760413-ef7e8584-8be0-11e7-8113-fe75afc15f30.png)

Using Cluster IP of vault service 
![image](https://user-images.githubusercontent.com/10971917/29760709-b5563076-8be2-11e7-902e-015d5ab3e345.png)

**Comment by F21** [comment]
From the error, it looks like you're not able to reach the `vault` hostname, so this is a DNS issue and unrelated to kubernetes-vault.

I am not familiar with your setup, but is your vault deployed at `vault.default.svc.cluster.local`? If so, that is the hostname you should be using.

**Comment by amolsh** [comment]
Using vault.default.svc.cluster.local

![image](https://user-images.githubusercontent.com/10971917/29760775-260844bc-8be3-11e7-8420-93eeac0817f9.png)

Does it have any relation with "vault auth" command, I fired this 2 days before and given value "vault-root-token"

**Comment by F21** [comment]
You cluster is not able to resolve the `vault` hostname. In your case, you will need to edit `kubernetes-vault.yaml`.

In https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/kubernetes-vault.yaml#L53, change `addr` to `http://vault.default.svc.cluster.local:8200`.

This seems to be due to the way your kubernetes cluster is set up, but if you change that setting, it should work correctly.

**Comment by amolsh** [comment]
I changed vault host and that error gone
Now, It is giving "permission denied, error in parsing token"
![image](https://user-images.githubusercontent.com/10971917/29761106-2c2e6590-8be5-11e7-9b37-6068d966b770.png)

Is it referring to this token, I have passed this token in kubernetes-vault.yml file -
![image](https://user-images.githubusercontent.com/10971917/29761126-4d70dbac-8be5-11e7-8ca9-fec17b07e241.png)


But this token generated is 2 days old, does is have an expiry

**Comment by F21** [comment]
The token is probably expired as it was generated a few days ago. The token policy is to expire every 6 hours.

You should generate a new token and apply it to `kubernetes-vault.yaml`.

**Comment by amolsh** [comment]
@F21 Thanks for great help and quick responses , It is  up now.
