### ISSUE TITLE
Create controller's token from an AppRole

### ISSUE THREAD

**Issue by awilliams** [Boostport/kubernetes-vault#84]
Currently, the token provided to the controller must be created using Vault's [_Token Auth Backend_](https://www.vaultproject.io/api/auth/token/index.html). The [documentation](https://github.com/Boostport/kubernetes-vault/blob/a0bbebacb0662042f3d7a01fe10400a37d30883a/deployments/quick-start/README.md#22-generate-the-token-for-kubernetes-vault) and [code](https://github.com/Boostport/kubernetes-vault/blob/199653a127519a34016c09e72b3165b5915c27a1/cmd/controller/client/vault.go#L276-L315) both show this.

Is there any reason not to allow, in addition to the _Token_ auth backend, a token created via the [_AppRole_](https://www.vaultproject.io/api/auth/approle/index.html) backend? If not, I'd be interested in submitting a PR to allow _AppRole_ in addition to _Token_ auth backends.

**Comment by F21** [comment]
Hey @awilliams 

Thanks for opening this issue. The kubernetes-vault controller currently requires an operator to get a token from Vault and pass it to the controller. It is possible for the operator to misuse the token in this case.

If we are using the AppRole backend, I imagine the operator would need to to pass the RoleID and SecretID to the controller. The controller would then need to exchange these 2 piece of information for a token. In this case, it is also possible for the operator to perform the exchange and misuse the token.

I think a better approach would be to use wrapped tokens as outlined in #81. In this case, the operator passes a wrapped token to the controller and does not get to see the real token. This approach seems to be easier to operate.

**Comment by awilliams** [comment]
Hi @F21,

Thanks for the response!

It's true that an operator could pass the `role_id` and `secret_id` to the controller, and then as you described have the controller fetch the token with these two ids. 

My intended use case was to have the **operator** fetch the token (in the same way described above), and then provide that token to the controller.

The issue I ran into with this approach is that the controller, when it [inspects the token](https://github.com/Boostport/kubernetes-vault/blob/199653a127519a34016c09e72b3165b5915c27a1/cmd/controller/client/vault.go#L276-L315), expects the token to have a "role" associated with it, otherwise it errors and exits. It then uses the "role" to ensure the token is renewable. 

Tokens created via an AppRole don't have a "role" field, but can still be renewable. The "renewability" of the token can also be checked in a similar way.

My proposal is to keep the existing functionality, but also support AppRole generated tokens.

[I've put together a bash script to be used against a local Vault dev server](https://gist.github.com/awilliams/bf3b6eaa279b1c121fc3ccf31104c8f4). It demonstrates how token's can be created and renewed using an AppRole as it applies to kubernetes-vault.

**Comment by F21** [comment]
Thanks for the explanation @awilliams! My apologies for the misunderstanding. That makes a lot more sense now.

Would you be able to make a PR for this?
