### ISSUE TITLE
kubernetes-vault not working with Kubernetes 1.8

### ISSUE THREAD

**Issue by chrw** [Boostport/kubernetes-vault#86]
Due to the deprecation of the alpha and beta annotations for Init Containers, kubernetes-vault is not working for us with Kubernetes 1.8.

They removed the annotation `pod.beta.kubernetes.io/init-container-statuses` and moved the status to `status.initContainerStatuses`.  See https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ at the bottom of the document. It wan't obvious in the CHANGELOG so we ran into it.

This annotation ist used to determine which Init Container needs a secret and it's used here: https://github.com/Boostport/kubernetes-vault/blob/master/cmd/controller/client/kube.go#L20

I don't have any Go experience but I'm trying to write a patch. Just want to let you know and maybe someone else has an idea or the skills to make a hotfix. 👍

**Comment by F21** [comment]
@chrw Thanks for reporting! I haven't had a chance to try 1.8 yet, but I will release a patch for this one.

**Comment by F21** [comment]
This is now released as `v0.5.0`. The docker images have also been published.

**Comment by chrw** [comment]
Wow. That was fast! 👍 
Thank you so much for the fix. It resolves our problem.
