### ISSUE TITLE
vault and pods are in different namespaces

### ISSUE THREAD

**Issue by ssinhas** [Boostport/kubernetes-vault#90]
I am  having an issue.
i am running vault in  default namespace ( future i  want  to  run  this in kube-suystem namespaces)

i have other pods running in different namespaces (like lmms-dev,  lmms-stage)
it doesn't work.  If i  deploy my  pods in default.. it works fine ..

do I have to  change anything? 
any help is really appreciated ..

**Comment by F21** [comment]
Hey @ssinhas 

If you are deploying things in different namespaces, you need to make sure the kubernetes-vault config for the vault address contains the full address (including the namespace).

You will need to change this line here: https://github.com/Boostport/kubernetes-vault/blob/master/deployments/quick-start/kubernetes-vault.yaml#L53

If Vault is running in the `system` namespace, then the `addr` should be `http://vault.system:8200`.

**Comment by ssinhas** [comment]
Yup  i  saw that and i fixed it..  thanks.. 

One thing i noticed though,  setup.sh  you  may  need to  add  some latency (sleep) after you use port  forwarding.. First time all  instructions after port forwarding failed.. 


Thanks again for your help.

**Comment by F21** [comment]
Glad you got it working. I'll see if I can put a better solution in place for the port forwarding. It currently just sleeps for 3 seconds.
