### ISSUE TITLE
getting secret throwing error

### ISSUE THREAD

**Issue by ssinhas** [Boostport/kubernetes-vault#91]
I have an issue... I am trying to extend sample app to read a secret from vault.

I am using 
"github.com/hashicorp/vault/api" library 

        client, err := api.NewClient(api.DefaultConfig())

        if err != nil {
            log.Fatal(err)
        }

        client.SetAddress(addr)
        client.SetToken(token.ClientToken)

token %t
 d763583a-b163-43cb-8d76-e1f8ee529347
Renewable: %t true

getting secret ...

error reading from vault: %s Error making API request.
URL: GET http://vault.kube-system:8200/v1/secret/backend/database
Code: 403. Errors:
* permission denied

Do you have any  example how I can read a secret from  vault?

**Comment by F21** [comment]
hey @ssinhas 

Reading/using secrets from Vault is outside the scope of this project. Kubernetes-Vault will get a Vault token into your pods, but you will need to write your own code or use a Vault client to read/write secrets.

In your case, you will need to use the [`Read()`](https://godoc.org/github.com/hashicorp/vault/api#Logical.Read) method from the logical backend.

You can also checkout the [vault-sidekick](https://github.com/UKHomeOffice/vault-sidekick) project to see how secrets are read from Vault using go.

**Comment by ssinhas** [comment]
I do understand that..  I am using Read function. My question is more like even I set up token i got it
from   Kubernetes-Vault,  why I am getting 403 error. It is permission error.

look at this line 

client.SetToken(token.ClientToken)

Where should I look into  it?

**Comment by F21** [comment]
If you are getting a 403, then it's possible that the approle for that token does not have the permission to access `secret/backend/database`. You will need to set the appropriate `token_policies` for the AppRole. I suggest having a look at the [AppRole documentation](https://www.vaultproject.io/docs/auth/approle.html).

**Comment by ssinhas** [comment]
i see one more issue...i tried to  auth  with token  generated in kubernets..
I see token plocy  is attached to  default

is it not supposed to  be kubernetes-vault?


token: ae60bf39-a1bd-cda4-12ce-563544164019
token_duration: 21464
token_policies: [default]

**Comment by F21** [comment]
The `kubernetes-vault` policy is only to be used by the controller to restrict what the kubernetes-vault controller can access. In your case, you need to create your own policies for each AppRole so that your pods can access the secrets it needs.

**Comment by ju187** [comment]
> i see one more issue...i tried to auth with token generated in kubernets..
> I see token plocy is attached to default
> 
> is it not supposed to be kubernetes-vault?
> 
> token: ae60bf39-a1bd-cda4-12ce-563544164019
> token_duration: 21464
> token_policies: [default]

I hit this too.  Did you have this worked out?  I tied the token with another program and got permission denied too.  Maybe you could give me some pointers.

**Comment by F21** [comment]
@ju187 It depends on what secrets you need to access using the token and the access/security policies of your organization. I suggest reading the following:
- https://www.vaultproject.io/docs/concepts/policies.html
- https://www.vaultproject.io/docs/auth/approle.html

**Comment by ju187** [comment]
I was playing with the kubernetes-vault, created some secrets and a policy for sample-app role

**Comment by F21** [comment]
You need to assign the policy to the role. See https://www.vaultproject.io/docs/auth/approle.html#via-the-api-1 if you're using the API.

**Comment by ju187** [comment]
Sure, Please close this thread
