### ISSUE TITLE
with tls set up setup.sh is failing

### ISSUE THREAD

**Issue by ssinhas** [Boostport/kubernetes-vault#94]
setup.sh was working fine. I have tear down and set up  vault many  times.,

Now I set up tls for vault and kubernetes-vault yaml file. 

I started getting 

Waiting for port forwarding to start
appending output to nohup.out

Error validating token: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/token/lookup-self
Code: 403. Errors:

* permission denied
Mount error: Error making API request.

URL: POST http://127.0.0.1:8200/v1/sys/mounts/root-ca
Code: 403. Errors:

* permission denied
Error writing data to root-ca/root/generate/internal: Error making API request.

**Comment by F21** [comment]
The `setup.sh` file is only suitable for running the quick start (which sets up vault over https). You will need to modify the `setup.sh` file if you want to use https and other customizations.

**Comment by ssinhas** [comment]
i fix most of the issues.  Lat  issue i  see  kubernets-vault pods is crashing.. 
I am getting this error

time="2017-11-03T15:21:06Z" level=debug msg="Discovered 0 nodes: []"
time="2017-11-03T15:21:06Z" level=fatal msg="Could not create the vault client: could not get vault root CAs: could not read CA certificates from the file vault.pem: open vault.pem: no such file or directory"


I can setting up 

vault:
  addr: http://vault:8200
  token: 91526d9b-4850-3405-02a8-aa29e74e17a5
  tls:
    caCert: vault.pem

My feeling you  are also  expecting volumeMounts for this file.

**Comment by F21** [comment]
From the error, it looks like you are pointing the kubernetes-vault controller to the vault.pem CA certificate, but it does not exist. In your case, you need to mount the vault.pem CA file into the pod so that kubernetes-vault can read it.
