### ISSUE TITLE
tls enabled but see this error

### ISSUE THREAD

**Issue by ssinhas** [Boostport/kubernetes-vault#97]
time="2017-11-17T00:40:43Z" level=debug msg="Discovered 0 nodes: []"
time="2017-11-17T00:40:43Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault.kube-system:8200/v1/auth/token/lookup-self: http: server gave HTTP response to HTTPS client"

This is coming from kubernetes vault pod log.

somewhere I have to  set up VAULT_ADDR  env variable ..
Not sure what should be the value...

**Comment by F21** [comment]
Try the following:

- From the error, `http: server gave HTTP response to HTTPS client`, check that Vault itself is also running in HTTPS mode.
- Make sure the CA certificate used to sign the certificate for the Vault server is available in `vault.tls.caCert`. See https://github.com/Boostport/kubernetes-vault/blob/master/deployments/secured-external-ca/kubernetes-vault.yaml#L51 for example config.

**Comment by F21** [comment]
Closing this as the issue has gone stale.
